# Generated by Django 5.2 on 2025-06-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='employee')),
            ],
        ),
    ]
