# Generated by Django 5.2 on 2025-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movielist'),
        ),
    ]
